# Generated by Django 4.2 on 2025-05-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sla', models.CharField(max_length=100)),
                ('tiempo_respuesta', models.PositiveIntegerField()),
                ('tiempo_resolucion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TICKET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=1000)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja'), ('Sin asignacion', 'Sin asignacion')], default='Sin asignacion', max_length=15)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En proceso', 'En proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=35)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_primera_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_asignado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_solicitante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL)),
                ('sla_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketera.sla')),
            ],
        ),
        migrations.CreateModel(
            name='REPORTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=255)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='COMENTARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketera.ticket')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
