# Generated by Django 4.2 on 2025-04-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketera', '0002_alter_ticket_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sla_aplicado',
        ),
    ]
