# Generated by Django 4.2 on 2025-05-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketera', '0002_ticket_sla_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sla_estado',
            field=models.CharField(choices=[('Sla en regla', 'Sla en regla'), ('Sla vencido', 'Sla vencido')], default='Sla en regla', max_length=35),
        ),
    ]
