# Generated by Django 4.2 on 2025-04-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketera', '0003_remove_ticket_sla_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketera.sla'),
        ),
    ]
