# Generated by Django 4.2 on 2025-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketera', '0004_ticket_sla_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sla',
            name='nombre_sla',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sla',
            name='tiempo_resolucion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sla',
            name='tiempo_respuesta',
            field=models.PositiveIntegerField(),
        ),
    ]
